"use client";
import { useState } from 'react';
import data from '@/lib/campus-timetable.json';
const DAYS = ['Mon','Tue','Wed','Thu','Fri'];
export default function CampusTimetable(){
 const [selected,setSelected]=useState('III AI ML');
 const rows=data.slots.filter(s=>s.className===selected);
 const roles=['CS Mentor 1','CS Mentor 2','CS Mentor 3','DS Mentor 1','DS Mentor 2','DS Mentor 3','BTech Mentor'];
 const names=['Younus SBS','Nishanta Kakati','Praveen Yadavalli','Aakaash M','Tamilarasan D','Parthajit Konwar','Abhilash'];
 return <div className="space-y-6"><header><p className="text-xs uppercase tracking-widest text-gray-500">Verified campus snapshot · {data.asOf}</p><h1 className="text-3xl font-bold mt-2">The campus week, clearly.</h1><p className="text-sm text-gray-600 mt-3">Eight classes. Seven sessions. Confirmed timetable changes, with no faculty clashes. PET remains in the final session.</p><a className="inline-block mt-3 text-sm underline" href="https://faceprep-campus-amet.vercel.app">Open live campus timetable ↗</a></header>
 <p className="rounded-lg border border-gray-200 bg-white p-4 text-sm text-gray-600">This is a dated copy of the operational timetable. The generator’s local planning data is separate and has not been overwritten.</p>
 <label htmlFor="campus-class" className="block text-sm font-semibold">Class</label><select id="campus-class" className="block mt-2 border rounded-lg p-3 bg-white w-full sm:w-80" value={selected} onChange={e=>setSelected(e.target.value)}>{data.classes.map(c=><option key={c}>{c}</option>)}</select>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[900px] text-sm"><caption className="text-left font-semibold p-4">{selected} · Weekly timetable</caption><thead><tr className="bg-gray-50"><th className="p-3 text-left">Session</th>{DAYS.map(d=><th className="p-3 text-left" key={d}>{d}</th>)}</tr></thead><tbody>{[1,2,3,4,5,6,7].map(n=><tr className="border-t align-top" key={n}><th className="p-3 text-left">S{n}<small className="block font-normal text-gray-500">{rows.find(s=>s.period===n)?.start}</small></th>{DAYS.map(day=>{const s=rows.find(s=>s.day===day&&s.period===n);return <td className="p-3 max-w-48" key={day}><span className="font-medium">{s?.subject||'—'}</span><small className="block mt-1 text-gray-500">{s?.faculty||'—'}</small></td>})}</tr>)}</tbody></table></div>
 <section><h2 className="text-xl font-semibold">Mentor allocation</h2><p className="text-sm text-gray-600 mt-2">Calculated from the timetable. Subject sessions and mentor hours are shown separately.</p><div className="overflow-x-auto mt-4 rounded-xl border bg-white"><table className="w-full min-w-[550px] text-sm"><thead><tr className="text-left bg-gray-50"><th className="p-3">Mentor</th><th>Subject sessions</th><th>Mentor hours</th><th>Total</th></tr></thead><tbody>{names.map((name,index)=>{const slots=data.slots.filter(s=>s.faculty===name);const mh=slots.filter(s=>['Mentor Hour','Mentor'].includes(s.subject)).length;return <tr className="border-t" key={name}><th className="p-3 text-left font-medium">{name}<small className="block font-normal text-gray-500">{roles[index]}</small></th><td>{slots.length-mh}</td><td>{mh}</td><td>{slots.length}</td></tr>})}</tbody></table></div><p className="text-sm mt-3 text-amber-800">Allocation check: Aakaash’s supplied allocation says 18; the named subjects occupy 13 sessions, plus one mentor hour. The five-session difference needs clarification.</p></section>
 </div>
}
